# ${opt:stage} - References the Environment that you would like to work with
# ${opt:ssm-store} - References the parent SSM Store location for your Vger Deployment e.g. devops-vger

service: vger-git-etl
provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage}
  region: us-east-1
  role: ${ssm:/${opt:ssm-store}/${opt:stage}/role}
  stackTags:
    TEAM: ${ssm:/${opt:ssm-store}/team}
  environment:
    DATABASE_NAME: ${ssm:/${opt:ssm-store}/redshift/${opt:stage}/database_name}
    REDSHIFT_PORT: ${ssm:/${opt:ssm-store}/redshift/${opt:stage}/port}
    AWS_RS_USER: ${ssm:/${opt:ssm-store}/redshift/${opt:stage}/username~true}
    AWS_RS_PASS: ${ssm:/${opt:ssm-store}/redshift/${opt:stage}/password~true}
    CLUSTER_ENDPOINT: ${ssm:/${opt:ssm-store}/redshift/${opt:stage}/cluster_endpoint}
    GIT_API_USER: ${ssm:/${opt:ssm-store}/git/${opt:stage}/api_user~true}
    GIT_API_KEY: ${ssm:/${opt:ssm-store}/git/${opt:stage}/api_key~true}
    ENV: ${opt:stage}
    # I would like to remove these credentials from this serverless call
    JH_JIRAURL: ${ssm:/${opt:ssm-store}/jira/${opt:stage}/host_url}
    JH_USER: ${ssm:/${opt:ssm-store}/jira/${opt:stage}/username~true}
    JH_PASS: ${ssm:/${opt:ssm-store}/jira/${opt:stage}/password~true}
package:
  individually: true

plugins:
  - serverless-package-python-functions  
custom:
  pkgPyFuncs: 
    buildDir: _build
    requirementsFile: 'requirements.txt'
    useDocker: true
    cleanup: true

functions:
  vger-sls-git-etl-scheduler:
    name: vger-sls-git-etl-scheduler-${self:provider.stage}
    handler: git_etl_scheduler.handler
    timeout: 300
    package:
      exclude:
        - "./**"
      include:
        - ./git_etl_scheduler
      artifact: ${self:custom.pkgPyFuncs.buildDir}/${self:functions.vger-sls-git-etl-scheduler.name}.zip

  vger-sls-git-etl-pr:
    name: vger-sls-git-etl-pr-${self:provider.stage}
    handler: git_etl_pr.handler
    timeout: 300
    package:
      exclude:
        - "./**"
      include:
        - ./git_etl_pr
        - ./constants
      artifact: ${self:custom.pkgPyFuncs.buildDir}/${self:functions.vger-sls-git-etl-pr.name}.zip

  vger-sls-git-etl-tag:
    name: vger-sls-git-etl-tag-${self:provider.stage}
    handler: git_etl_tag.handler
    timeout: 300
    package:
      exclude:
        - "./**"
      include:
        - ./git_etl_tag
        - ./constants
      artifact: ${self:custom.pkgPyFuncs.buildDir}/${self:functions.vger-sls-git-etl-tag.name}.zip
