# ${opt:stage} - References the Environment that you would like to work with
# ${opt:ssm-store} - References the parent SSM Store location for your Vger Deployment e.g. devops-vger

service: vger-jira-etl
provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage}
  region: us-east-1
  role: ${ssm:/${opt:ssm-store}/${opt:stage}/role}
  stackTags:
    TEAM: ${ssm:/${opt:ssm-store}/team}
  environment:
    #    why do we need to provide extra credentials here?
    DATABASE_NAME: ${ssm:/${opt:ssm-store}/redshift/${opt:stage}/database_name}
    REDSHIFT_PORT: ${ssm:/${opt:ssm-store}/redshift/${opt:stage}/port}
    AWS_RS_USER: ${ssm:/${opt:ssm-store}/redshift/${opt:stage}/username~true}
    AWS_RS_PASS: ${ssm:/${opt:ssm-store}/redshift/${opt:stage}/password~true}
    CLUSTER_ENDPOINT: ${ssm:/${opt:ssm-store}/redshift/${opt:stage}/cluster_endpoint}
    JH_JIRAURL: ${ssm:/${opt:ssm-store}/jira/${opt:stage}/host_url}
    JH_USER: ${ssm:/${opt:ssm-store}/jira/${opt:stage}/username~true}
    JH_PASS: ${ssm:/${opt:ssm-store}/jira/${opt:stage}/password~true}
    ENV: ${opt:ssm-store}
    # I would like to remove these parameters from this serverless call
    GIT_API_USER: ${ssm:/${opt:ssm-store}/git/${opt:stage}/api_user~true}
    GIT_API_KEY: ${ssm:/${opt:ssm-store}/git/${opt:stage}/api_key~true}
package:
  individually: true

plugins:
  - serverless-package-python-functions  
custom:
  pkgPyFuncs: 
    buildDir: _build
    requirementsFile: 'requirements.txt'
    globalIncludes:
      - ./lib
    useDocker: true
    cleanup: true


functions:
  vger-sls-jira-etl-scheduler:
    name: vger-sls-jira-etl-scheduler-${self:provider.stage}
    handler: jira_etl_scheduler.handler
    timeout: 300
    package:
      exclude:
        - "./**"
      include:
        - ./jira_etl_scheduler
      artifact: ${self:custom.pkgPyFuncs.buildDir}/${self:functions.vger-sls-jira-etl-scheduler.name}.zip
    
  vger-sls-jira-etl:
    name: vger-sls-jira-etl-${self:provider.stage}
    handler: jira_extract.handler
    timeout: 300
    package:
      exclude:
        - "./**"
      include:
        - ./jira_etl
        - ./constants
      artifact: ${self:custom.pkgPyFuncs.buildDir}/${self:functions.vger-sls-jira-etl.name}.zip

  vger-sls-jira-issue-type-etl:
    name: vger-sls-jira-issue-type-etl-${self:provider.stage}
    handler: jira_issue_type_etl.handler
    timeout: 300
    package:
      exclude:
        - "./**"
      include:
        - ./jira_issue_type_etl
      artifact: ${self:custom.pkgPyFuncs.buildDir}/${self:functions.vger-sls-jira-issue-type-etl.name}.zip